config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "workspaces#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/workspaces/my_workspaces', to: 'workspaces#my_workspaces'
  resources :workspaces do
    resources :bookings, only: [:create]
    resources :reviews, only: [:create]
  end
  resources :bookings, only: [:destroy, :index]
  resources :favourites, only: [:index, :destroy, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :workspace
  validates :booking_status, inclusion: { in: %w(requested accepted declined), message: "Not a valid response" }
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :workspace
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :workspace
  validates :content, length: { minimum: 20 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :workspaces, dependent: :destroy
  has_many :favourites, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/workspace.rb
class Workspace < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :favourites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  belongs_to :user
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model

  pg_search_scope :search_by_address_and_description,
    against: [ :address, :description ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings
  end
  # removed as we handle new bookings in the workspace controller
  # def new
  #   @workspace = Workspace.find(params[:workspace_id])
  #   @booking = Booking.new
  # end

  def create
    @workspace = Workspace.find(params[:workspace_id])
    @booking = Booking.new(strong_params)
    @booking.workspace = @workspace
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

  private

  def strong_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController

  def index
    @favourites = current_user.favourites
  end

    def create
      @favourite = Favourite.create(workspace_id: params[:workspace_id], user_id: current_user.id)
      redirect_back fallback_location: workspaces_path
    end

    def destroy
      @favourite = Favourite.find(params[:id])
      @favourite.destroy
      redirect_back fallback_location: workspaces_path
    end

    # private



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def create
        @workspace = Workspace.find(params[:workspace_id])
        @review = Review.new(review_params)
        @review.workspace = @workspace
        if @review.save
            redirect_to workspace_path(@workspace)
        else
            render "workspaces/show", status: :unprocessable_entity
        end
    end

private

    def review_params
        params.require(:review).permit(:content, :rating)
    end
end

app/controllers/workspaces_controller.rb
class WorkspacesController < ApplicationController
  def index
    if params[:query].present?
      @workspaces = Workspace.search_by_address_and_description(params[:query])
      @markers = @workspaces.geocoded.map do |workspace|
      {
          lat: workspace.latitude,
          lng: workspace.longitude,
      }
      end
    else
      @workspaces = Workspace.all
      @markers = @workspaces.geocoded.map do |workspace|
      {
          lat: workspace.latitude,
          lng: workspace.longitude,
      }
    end
    end
  end

  def show
    @workspace = Workspace.find(params[:id])
    @booking = Booking.new
    @review = Review.new
  end

  def new
    @workspace = Workspace.new
  end

  def create
    @workspace = Workspace.new(strong_params)
    @user = current_user
    @workspace.user = @user
    if @workspace.save
      redirect_to workspace_path(@workspace)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @workspace = Workspace.find(params[:id])
    @workspace.destroy
    redirect_to workspaces_path, status: :see_other
  end

  def edit
    @workspace = Workspace.find(params[:id])
  end

  def update
    @workspace = Workspace.find(params[:id])
    @workspace.update(strong_params)
    redirect_to workspace_path(@workspace)
  end

  def my_workspaces
    user = current_user
    @workspaces = user.workspaces
  end

  private

  def strong_params
    params.require(:workspace).permit(:name, :price, :address, :description, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12 bold">
      <h1><strong>My bookings</strong></h1>

    </div>
  </div>

  <div class="row">
    <% @bookings.each do |booking| %>
      <div class="col-md-4">
        <a class="plain-link" href="<%=workspace_path(booking.workspace_id)%>">
        <div class="flat-card">
          <% if booking.workspace.photos.attached? %>
            <div class="flat-card-image" style="background-image: url('<%= cl_image_path booking.workspace.photos[0].key, crop: :fill %>')"></div>
          <% else %>
            <div class="flat-card-image" style="background-image: url('https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1744&q=80')"></div>
          <% end %>
            <%= link_to booking_path(booking), style: "color: #5A5A5A; position: absolute; top: 4px; right: 8px;", class: "my-0", data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to cancel your desk?"} do %>
              <i class="fa-regular fa-circle-xmark"></i>
            <% end %>
          <div class="flat-card-content" style="overflow: hidden; height:220px;">
            <div class="booking-workspace-title">
              <h4><%= booking.workspace.name %></h4>
            </div>
            <div class="flex-align booking-medium-text"">
              <p><%= booking.workspace.address %></p>
            </div>
            <div class="flex-align booking-small-text">
              <p class = "my-0"><%= booking.start_date.strftime("%-d<sup><suffix></sup> %B %Y").html_safe %> - <%= booking.end_date.strftime("%-d<sup><suffix></sup> %B %Y").html_safe %></p>
            </div>
            <div class="flex-align days-until">
              <p><%= pluralize((booking.start_date - Date.today).to_i, "day") %> from today!</p>
            </div>
            <div class="flex-align booking-small-text bold">
              <%# <span>£<%= booking.workspace.price.round %></span>
              <span>£<%= ((booking.end_date - booking.start_date + 1) * booking.workspace.price).round %> total (£<%=booking.workspace.price.round%> / day) </span>
            </div>
          </div>
        </div>
      </a>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<p>we will need to have a select start and end date for the booking</p>
      <%= simple_form_for [@workspace, @booking] do |f| %>
        <%= f.input :start_date %>
        <%= f.input :end_date %>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>

app/views/favourites/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12 bold">
      <h1><strong><%= current_user.first_name.capitalize %>'s Wishlist</strong></h1>

    </div>
  </div>

  <div class="row">
    <% @favourites.each do |favourite| %>
      <div class="col-md-4">
        <a class="plain-link" href="<%=workspace_path(favourite.workspace_id)%>">
        <div class="flat-card">
          <div class="flat-card-image" style="background-image: url('<%= cl_image_path favourite.workspace.photos[0].key, crop: :fill %>')"></div>
            <%= link_to favourite_path(favourite), style: "color: #FF0000; position: absolute; top: 4px; right: 8px; opacity: 0.8", class: "my-0", data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to remove from your Wishlist?"} do %>
              <i class="fa-solid fa-heart fa-lg"></i>
            <% end %>
          <div class="flat-card-content" style="overflow: hidden; height: 180px;">
            <div class="booking-workspace-title">
              <h4><%= favourite.workspace.name %></h4>
            </div>
            <div class="flex-align booking-medium-text">
              <p><%= favourite.workspace.address %></p>
            </div>
            <a class="btn btn-primary" href="<%=workspace_path(favourite.workspace_id)%>">Reserve this desk!</a>

          </div>
        </div>
      </a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkFromHomeIsh</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application.js", "data-turbo-track": "reload", defer: true %>

    <%# added by Sam to fix JS error in heroku %>
    <%# <%= javascript_include_tag "bootstrap" if Rails.env.development? %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>


  </head>

  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand logo" href="/workspaces">
      <%= image_tag "desk_logo.png"%>
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse mx-auto">
     <%= form_with url: workspaces_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a desk"
      %>
      <%= submit_tag "Search", class: "btn btn-primary a:hover" %>
      <% end %>
    </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto">
          <%# <li class="nav-item active">
            <a class="nav-link" href="#">Home</a>
          </li> %>
          <%# <li class="nav-item">
            <a class="nav-link" href="#">Support</a>
          </li> %>
      <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://res.cloudinary.com/crunchbase-production/image/upload/c_thumb,h_256,w_256,f_auto,g_faces,z_0.7,q_auto:eco,dpr_1/itkf94aza2outbuythpx" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Wishlist (#{current_user.favourites.count})", "/favourites", class: "dropdown-item" %>
              <%= link_to "My bookings (#{current_user.bookings.count})", "/bookings", class: "dropdown-item" %>
              <%= link_to "My workspaces (#{current_user.workspaces.count})", workspaces_my_workspaces_path, class: "dropdown-item" %>
              <%= link_to "Add Workspace", new_workspace_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item dropdown">
              <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://res.cloudinary.com/crunchbase-production/image/upload/c_thumb,h_256,w_256,f_auto,g_faces,z_0.7,q_auto:eco,dpr_1/itkf94aza2outbuythpx" />
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Action", "#", class: "dropdown-item" %>
                <%= link_to "Another action", "#", class: "dropdown-item" %>
                <%= link_to "Login", new_user_session_path, class: "dropdown-item" %>
              </div>
          </li>
        <% end %>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>

  <body>
    <%= render "shared/flashes" %>
    <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/workspaces/edit.html.erb
<div id="wrapper" class="d-flex justify-content-center">
  <div class="row">
    <div class="text-left form-login">
      <h2 class="text-center"><strong>Add my Workspace</strong></h2>
      <br>
      <%= simple_form_for @workspace do |f| %>
      <%= f.error_notification %>
      <%= f.input :name, placeholder: "Name of my amazing Workspace", :label_html => { :class => "label-css"} %>
      <%= f.input :address, label: "Located in:", placeholder: "London" %>
      <%= f.input :description, label: "Description of my place:", placeholder: "Beautiful workspace with coffee on tap" %>
      <%= f.input :price, label: "Price per hour in £", placeholder: "24" %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <br>
      <br>
      <hr>
      <h4><strong></strong> </h4>
      <hr>
      <div class="d-flex text-center">
      <%= f.button :submit, "update my workspace", class: "btn btn-primary btn-lg"%>
      </div>

      <% end %>
    </div>
  </div>

</div>
</div>

app/views/workspaces/index.html.erb
<button onclick="myFunction()" id ="showmap" class="btn btn-primary vertical-center" style="border-radius: 30px;">Show map 🗺️</button>

<div class="banner m-0">
  <%# <div class="row padding-landing" style="background-image: linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.5)), url('https://images.unsplash.com/photo-1590166045671-9bb0c0a76ea4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80'); background-size: 1449px auto;">
      <div class="col-12 title-index-padding">
        <h1 class="landing-page-title">Work from home.</h1>
        <h1 class="landing-page-title-2 typing-effect"><strong>Anywhere.</strong></h1>
      </div>
    </div> %>

    <div id="map" class="m-0"
      data-controller="map"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
      style="width: 98%; height: 600px; margin: 10px;"
      data-map-markers-value="<%= @markers.to_json %>">
    </div>
</div>

<div class="flex-container mt-3">
  <div class="col-sm-9 mx-auto">
    <!-- flat cards section -->
        <div class="row">
          <% @workspaces.each do |workspace| %>
          <div class="col-md-3">
            <a class="plain-link" href="<%= workspace_path(workspace) %>">
              <div class="flat-card">
                <% if workspace.photos.attached? %>
                  <div class="flat-card-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path workspace.photos[0].key, crop: :fill, cloud_name: "damvdcvup" %>')"></div>
                <% else %>
                  <div class="flat-card-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1542315192-1f61a1792f33?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80')"></div>
                <% end %>
                <% if user_signed_in? %>
                  <% if current_user.favourites.find_by(workspace_id: workspace.id) %>
                    <%= link_to favourite_path(current_user.favourites.find_by(workspace_id: workspace.id)), style: "color: #FF0000; position: absolute; top: 4px; right: 8px; opacity: 0.8", class: "my-0", data: {turbo_method: :delete} do %>
                    <i class="fa-solid fa-heart fa-lg"></i>
                    <% end %>
                  <% else %>
                  <%= link_to favourites_path(workspace_id: workspace.id), style: "color: #FFFFFF; position: absolute; top: 4px; right: 8px; opacity: 0.8", class: "my-0", data: {turbo_method: :post} do %>
                    <i class="fa-regular fa-heart fa-lg"></i>
                    <% end %>
                  <% end %>
                <% end %>
                <div class="flat-card-content" style="overflow: hidden;">
                  <div class="booking-workspace-title">
                    <h6><%= workspace.name %></h6>
                  </div>
                  <div class="flex-align booking-medium-text">
                    <p><%= workspace.address %></p>
                  </div>
                  <div class="flex-align">
                    <div class="flex-align booking-small-text bold">
                      <span>£<%= workspace.price%>0 / day</span>
                    </div>
                  </div>
                </div>
              </div>
            </a>
          </div>
        <% end %>
        </div>
  </div>


<script>
function myFunction() {
  var x = document.getElementById("map");
  if (x.classList.contains("d-none")) {
    document.getElementById("map").classList.remove("d-none");
    document.getElementById("showmap").innerText = "Show desks 💻"
  } else {
    document.getElementById("map").classList.add("d-none");
    document.getElementById("showmap").innerText = "Show map 🗺️"
  }
}
</script>

app/views/workspaces/show.html.erb
<%= stylesheet_link_tag "application" %>
<% if @workspace.photos.attached? %>
  <div class="map" style="background-image: url('<%= cl_image_path @workspace.photos[0].key, crop: :fill %>')"></div>
<% else %>
  <div class="map" style="background-image: url('https://images.unsplash.com/photo-1497366811353-6870744d04b2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1469&q=80')"></div>
<% end %>

<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="flat-show-card">
        <h1><font color="black"><b><%= @workspace.name %></b></h1></font>
        <p class="flat-show-address"><font color="grey"><%= @workspace.address %></font></p>
      </div>
      <div class="flat-show-card">
        <h3>A bit more about this desk to rent...</h3>
        <p><%= @workspace.description %></p>
        <% if @workspace.photos.attached? %>
          <% count = @workspace.photos.count %>
          <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
            <div class="carousel-indicators">
              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <% (1...count).each do |counter| %>
                  <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="<%= counter %>" aria-label="Slide 2"></button>
                <% end %>
            </div>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img class="d-block workspace_show_images w-100 " src="<%= cl_image_path @workspace.photos[0].key, crop: :fill %>" alt="First slide">
              </div>
              <% (1...count).each do |counter| %>
                <div class="carousel-item">
                  <img class="d-block workspace_show_images w-100" src="<%= cl_image_path @workspace.photos[counter].key, crop: :fill %>" alt="Second slide">
                </div>
              <% end %>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        <% else %>
          <div class="map" style="background-image: url('https://cdn.autonomous.ai/static/upload/images/common/upload/20210918/10-Gaming-Desk-Setup-Hacks-for-Every-Gamer_55ff4d6937e.jpg'")></div>
        <% end %>
      </div>
    </div>

    <div class="col-4">
      <% if current_user != @workspace.user %>
        <div class="flat-show-card">
          <div class="booking-header">
            <h3><b>Make your booking</b></h3>
            <% if user_signed_in? %>
              <% if current_user.favourites.find_by(workspace_id: @workspace.id) %>
                <%= link_to favourite_path(current_user.favourites.find_by(workspace_id: @workspace.id)), style: "color: #FF0000;", class: "my-0", data: {turbo_method: :delete} do %>
                <i class="fa-solid fa-heart fa-lg"></i>
                <% end %>
              <% else %>
              <%= link_to favourites_path(workspace_id: @workspace.id), style: "color: #FF0000;", class: "my-0", data: {turbo_method: :post} do %>
                <i class="fa-regular fa-heart fa-lg"></i>
                <% end %>
              <% end %>
            <% end %>
            <%# <div id="onhoverheart">Add to Wishlist</div> %>
          </div>
          <%= simple_form_for [@workspace, @booking] do |f| %>
            <%= f.input :start_date, as: :date, html5: true  %>
            <%= f.input :end_date, as: :date, html5: true  %>
            <%= f.submit 'Reserve Workspace', class: 'btn btn-primary' %>
          <% end %>
        </div>
      <% end %>

        <%# <form action="">
          <div class="input-group">
            <span class="input-group-text" id="start-date-label">From:</span>
            <input type="text" class="form-control" placeholder="06/03/2022" aria-label="start-date" aria-describedby="start-date-label">
          </div>
          <div class="input-group mt-2">
            <span class="input-group-text" id="end-date-label">To:</span>
            <input type="text" class="form-control" placeholder="06/03/2022" aria-label="end-date" aria-describedby="start-date-label">
          </div>
          <input type="submit" value="Book" class="btn btn-primary mt-2" style="width: 100%">
        </form> %>

      <div class="flat-show-card">
        <h3><b>Details</b></h3>
        <div class="flex">
          <div class="flex">
            <p><font color="green"><%= "Available" %></font></p>
          </div>
        </div>
        <div class="flex">
          £<%= @workspace.price.round %> per day
        </div>

      </div>
      <div class="flat-show-card">
        <div class="flex-align">
          <h6 class="no-mb">Share</h6>

          <div class="flex">
            <i class="fa-brands fa-facebook-square me-2"></i>
            <i class="fa-brands fa-twitter-square me-2"></i>
            <i class="fa-brands fa-pinterest-square me-2"></i>
          </div>
        </div>
      </div>
      <% if current_user == @workspace.user %>
        <div class="flat-show-card">
            <div class="flex-align">
              <%= link_to 'Edit Workspace', edit_workspace_path(@workspace), style: 'color: #0D6EFD ; text-decoration: none;' %>
              <%= link_to "Delete Workspace", workspace_path(@workspace), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, style: 'color: #ff0000; text-decoration: none;'%>
            </div>
          </div>
        <% end %>

    </div>

<div class="review-card d-flex-align">
<h1>Reviews</h1>
<h4><strong><%= pluralize @workspace.reviews.size, "review" %></strong></h4>

  <% if @workspace.reviews.blank? %>
    Be the first to leave a review for <%= @workspace.name %>
  <% else %>
    <% @workspace.reviews.each do |review| %>
      <div class="review">
        <p class="content"><%= review.content %></p>
        <div class="rating">
          <% if review.rating.present? %>
            <% review.rating.round.times do %>
              <i class="fa-solid fa-star"></i>
            <% end %>
            <% (5 - review.rating).round.times do %>
              <i class="fa-regular fa-star"></i>
            <% end %>
          <% else %>
            No rating
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
  <h4><strong>Leave a review</strong></h4>
  <div class="review-form"> 
    <%= simple_form_for([@workspace, @review]) do |f| %>
      <%= f.input :content %>
      <%= f.input :rating %>
      <%= f.submit 'Leave a review', class: 'btn btn-primary' %>
    <% end %>
  </div> 
</div>


  </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>